name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Gradle Wrapper setup
      run: gradle wrapper

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
    - name: kill adb server
      run: adb kill-server
      
    - name: kill adb server
      run: adb start-server


    - name: Android Emulator Runner
      uses: ReactiveCircus/android-emulator-runner@v2.27.0
      env:
          GRADLE_OPTS: "-Dorg.gradle.internal.http.connectionTimeout=60000 -Dorg.gradle.internal.http.socketTimeout=60000 -Dorg.gradle.internal.network.retry.max.attempts=6 -Dorg.gradle.internal.network.retry.initial.backOff=2000"
      with:
        api-level: 33
        target: google_apis
        arch: x86_64
        profile: pixel_2
        ndk: 21.4.7075529
        ram-size: '4096M'
        disk-size: '14G'
        sdcard-path-or-size: '1000M'
        disable-animations: false
        script: bash contrib/instrumentation.sh
